version: '3.8'

services:
  langgraph-playground:
    build: .
    container_name: langgraph-playground
    ports:
      - "2024:2024"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - ROOT_PATH=/langgraphplayground
    volumes:
      - ./src:/app/src
      - ./data:/app/data  # For persistent storage if needed
    restart: unless-stopped
    networks:
      - langgraph-net

networks:
  langgraph-net:
    driver: bridge
